
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 12 20:02:19 BOT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Tangente = 7;
  public static final int Seno = 6;
  public static final int Error = 8;
  public static final int EOF = 0;
  public static final int Coseno = 5;
  public static final int Identificador = 2;
  public static final int error = 1;
  public static final int Igual = 3;
  public static final int Numero = 4;
}

